### ISSUE TITLE
Webhook Error on bolna dashboard after Adding followup task extraction and webhook, adding webhook url.  

### ISSUE THREAD

**Issue by orion-satyammishra** [voxos-ai/bolna#187]
Uncaught TypeError: Cannot read properties of undefined (reading 'webhook')
    at utils.js:406:125
    at Array.forEach (<anonymous>)
    at utils.js:405:54
    at Array.forEach (<anonymous>)
    at utils.js:397:19
    at tI (utils.js:423:30)
    at R0 (AgentDetails.js:21:44)
    at mi (react-dom.production.min.js:167:137)
    at mc (react-dom.production.min.js:290:337)
    at Ol (react-dom.production.min.js:280:389)

**Comment by prateeksachan** [comment]
this is fixed now. Thanks for reporting it @orion-satyammishra
